---

motd_info:
  - "   FQDN:    ": "{{ ansible_fqdn }}"
  - "   IP:      ": "{{ ansible_default_ipv4.address }}"
  - "   Distro:  ": "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  - "   Virtual: ": "{{ 'YES' if ansible_virtualization_role == 'guest' else 'NO' }}"
  - "   CPUs:    ": "{{ ansible_processor_vcpus }}"
  - "   RAM:     ": "{{ (ansible_memtotal_mb / 1000) | round(1) }}GB"


motd_content: |
  --------------------------------------------------------------------------
                This system is managed by Satellite and Ansible
  --------------------------------------------------------------------------

  NOTE: System and application configuration for this host is managed by
  automated systems. To ensure that any changes you make here are not lost,
  please contact your system administrators.

  {% for item in motd_info %}
  {% for key, value in item.iteritems() %}
  {{ key }}{{ value }}
  {% endfor %}
  {% endfor %}

  --------------------------------------------------------------------------
  Last ansible run: {{ ansible_date_time.iso8601 }}
